name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write  # Permisos para que GitHub Actions pueda hacer push de los cambios

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Tonx117
          # Genera los archivos en una rama llamada "output". Esto evita que la rama principal se llene de archivos.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Muestra el estado de los archivos. Esto facilita la depuración si surge algún problema.
      - run: git status

      # Empuja los cambios a la rama master
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Publica los archivos en la rama output
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # La rama de salida que mencionamos anteriormente
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
